"""Removed ondelete, onupdate options for fkeys in holiday_states for testing

Revision ID: c1cbefb4c2a1
Revises: 10074aca99a3
Create Date: 2025-06-12 01:31:53.588655

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c1cbefb4c2a1"
down_revision: Union[str, None] = "10074aca99a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("holidays_states_holiday_id_fkey"), "holidays_states", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("holidays_states_state_id_fkey"), "holidays_states", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("holidays_states_holiday_id_fkey"),
        "holidays_states",
        "holidays",
        ["holiday_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("holidays_states_state_id_fkey"),
        "holidays_states",
        "states",
        ["state_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("holidays_states_holiday_id_fkey"), "holidays_states", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("holidays_states_state_id_fkey"), "holidays_states", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("holidays_states_state_id_fkey"),
        "holidays_states",
        "states",
        ["state_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("holidays_states_holiday_id_fkey"),
        "holidays_states",
        "holidays",
        ["holiday_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
