"""Added column type to holidays

Revision ID: 226b977c1746
Revises: e9fad61b050e
Create Date: 2025-06-10 13:13:55.524970

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "226b977c1746"
down_revision: Union[str, None] = "e9fad61b050e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("holidays", sa.Column("type", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("holidays", "type")
    # ### end Alembic commands ###
