"""Added cascade option on operations

Revision ID: e9fad61b050e
Revises: 876517eb9809
Create Date: 2025-06-10 12:26:26.450937

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e9fad61b050e"
down_revision: Union[str, None] = "876517eb9809"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("holidays_states_state_id_fkey"), "holidays_states", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("holidays_states_holiday_id_fkey"), "holidays_states", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("holidays_states_holiday_id_fkey"),
        "holidays_states",
        "holidays",
        ["holiday_id"],
        ["id"],
        onupdate="cascade",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("holidays_states_state_id_fkey"),
        "holidays_states",
        "states",
        ["state_id"],
        ["id"],
        onupdate="cascade",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("holidays_states_holiday_id_fkey"), "holidays_states", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("holidays_states_state_id_fkey"), "holidays_states", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("holidays_states_holiday_id_fkey"),
        "holidays_states",
        "holidays",
        ["holiday_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("holidays_states_state_id_fkey"),
        "holidays_states",
        "states",
        ["state_id"],
        ["id"],
    )
    # ### end Alembic commands ###
